{
 "title": "CIP Adoption",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "aggregate", "label": "Aggregate By", "query": "compartment,region" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(oci_instance_total, region)"
    }
   },
   {
    "name": "compartment",
    "label": "Compartment",
    "query": {
     "query": "label_values(oci_instance_total, compartment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CIP Inst. %",
   "type": "gauge",
   "description": "Overall percentage of instances that are CIP based",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (oci_instance_cip_based)) / (sum (oci_instance_total{oci_instance_defined_tag_OracleDataCloud_isProduction=\"\", oci_instance_defined_tag_OracleDataCloud_clusterId=\"\", oci_instance_defined_tag_OracleDataCloud_teamId=\"\", oci_instance_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_instance_defined_tag_OracleDataCloud_origin=\"\", oci_instance_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_instance_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_instance_defined_tag_OracleDataCloud_product=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (oci_instance_total{oci_instance_defined_tag_OracleDataCloud_isProduction=\"\", oci_instance_defined_tag_OracleDataCloud_clusterId=\"\", oci_instance_defined_tag_OracleDataCloud_teamId=\"\", oci_instance_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_instance_defined_tag_OracleDataCloud_origin=\"\", oci_instance_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_instance_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_instance_defined_tag_OracleDataCloud_product=\"\"})"
    }
   ]
  },
  {
   "title": "CIP Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (oci_instance_cip_based)" }
   ]
  },
  {
   "title": "CIP Img. %",
   "type": "gauge",
   "description": "Overall percentage of images that are CIP based",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (oci_image_cip_based)) / (sum (oci_image_total{oci_image_defined_tag_OracleDataCloud_isProduction=\"\", oci_image_defined_tag_OracleDataCloud_clusterId=\"\", oci_image_defined_tag_OracleDataCloud_teamId=\"\", oci_image_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_image_defined_tag_OracleDataCloud_origin=\"\", oci_image_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_image_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_image_defined_tag_OracleDataCloud_product=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (oci_image_total{oci_image_defined_tag_OracleDataCloud_isProduction=\"\", oci_image_defined_tag_OracleDataCloud_clusterId=\"\", oci_image_defined_tag_OracleDataCloud_teamId=\"\", oci_image_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_image_defined_tag_OracleDataCloud_origin=\"\", oci_image_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_image_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_image_defined_tag_OracleDataCloud_product=\"\"})"
    }
   ]
  },
  {
   "title": "CIP Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (oci_image_cip_based)" }
   ]
  },
  {
   "title": "Inst. Comp.",
   "type": "stat",
   "description": "Number of compartments containing instances.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (compartment) (oci_instance_total))"
    }
   ]
  },
  {
   "title": "Img. Comp.",
   "type": "stat",
   "description": "Number of compartments containing custom images.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (compartment) (oci_image_total))"
    }
   ]
  },
  {
   "title": "Inst. Regions.",
   "type": "stat",
   "description": "Number of regions containing instances.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (region) (oci_instance_total))"
    }
   ]
  },
  {
   "title": "Img. Regions.",
   "type": "stat",
   "description": "Number of regions containing custom images.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (region) (oci_image_total))"
    }
   ]
  },
  { "title": "Instances (Aggregated)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ($aggregate) (oci_instance_total{region=~\"$region\", compartment=~\"$compartment\", oci_instance_defined_tag_OracleDataCloud_isProduction=\"\", oci_instance_defined_tag_OracleDataCloud_clusterId=\"\", oci_instance_defined_tag_OracleDataCloud_teamId=\"\", oci_instance_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_instance_defined_tag_OracleDataCloud_origin=\"\", oci_instance_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_instance_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_instance_defined_tag_OracleDataCloud_product=\"\"})",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  {
   "title": "CIP Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ($aggregate) (oci_instance_cip_based{region=~\"$region\", compartment=~\"$compartment\"})",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  {
   "title": "CIP Instance %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by ($aggregate) (oci_instance_cip_based{region=~\"$region\", compartment=~\"$compartment\"})) / (sum by ($aggregate) (oci_instance_total{region=~\"$region\", compartment=~\"$compartment\", oci_instance_defined_tag_OracleDataCloud_isProduction=\"\", oci_instance_defined_tag_OracleDataCloud_clusterId=\"\", oci_instance_defined_tag_OracleDataCloud_teamId=\"\", oci_instance_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_instance_defined_tag_OracleDataCloud_origin=\"\", oci_instance_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_instance_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_instance_defined_tag_OracleDataCloud_product=\"\"}))",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  { "title": "Images (Aggregated)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Images",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ($aggregate) (oci_image_total{region=~\"$region\", compartment=~\"$compartment\", oci_image_defined_tag_OracleDataCloud_isProduction=\"\", oci_image_defined_tag_OracleDataCloud_clusterId=\"\", oci_image_defined_tag_OracleDataCloud_teamId=\"\", oci_image_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_image_defined_tag_OracleDataCloud_origin=\"\", oci_image_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_image_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_image_defined_tag_OracleDataCloud_product=\"\"})",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  {
   "title": "CIP Images",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ($aggregate) (oci_image_cip_based{region=~\"$region\", compartment=~\"$compartment\"})",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  {
   "title": "CIP Image %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by ($aggregate) (oci_image_cip_based{region=~\"$region\", compartment=~\"$compartment\"})) / (sum by ($aggregate) (oci_image_total{oci_image_defined_tag_OracleDataCloud_isProduction=\"\", oci_image_defined_tag_OracleDataCloud_clusterId=\"\", oci_image_defined_tag_OracleDataCloud_teamId=\"\", oci_image_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_image_defined_tag_OracleDataCloud_origin=\"\", oci_image_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_image_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_image_defined_tag_OracleDataCloud_product=\"\"}))",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  { "title": "Storage Resources (Aggregated)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Buckets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ($aggregate) (oci_bucket_total{region=~\"$region\", compartment=~\"$compartment\", oci_instance_defined_tag_OracleDataCloud_isProduction=\"\", oci_instance_defined_tag_OracleDataCloud_clusterId=\"\", oci_instance_defined_tag_OracleDataCloud_teamId=\"\", oci_instance_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_instance_defined_tag_OracleDataCloud_origin=\"\", oci_instance_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_instance_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_instance_defined_tag_OracleDataCloud_product=\"\"})",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  },
  {
   "title": "Total Block Volumes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by ($aggregate) (oci_block_volume_total{region=~\"$region\", compartment=~\"$compartment\", oci_instance_defined_tag_OracleDataCloud_isProduction=\"\", oci_instance_defined_tag_OracleDataCloud_clusterId=\"\", oci_instance_defined_tag_OracleDataCloud_teamId=\"\", oci_instance_defined_tag_OracleDataCloud_CSSAPProjectNumber=\"\", oci_instance_defined_tag_OracleDataCloud_origin=\"\", oci_instance_defined_tag_OracleDataCloud_dataSensitivity=\"\", oci_instance_defined_tag_OracleDataCloud_vaultAuthRole=\"\", oci_instance_defined_tag_OracleDataCloud_product=\"\"})",
     "legendFormat": "{{$aggregate}}"
    }
   ]
  }
 ]
}