{
 "title": "Cluster Capacity",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Datasource" },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 46 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 46 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 52 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 58 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 64 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 85 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 85 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 85 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 91 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 91 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 97 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 103 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 118 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 124 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 124 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 124 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 130 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 130 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 130 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 130 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 136 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 136 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 142 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 157 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 163 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 163 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 163 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 163 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 169 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 169 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 169 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 169 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 175 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 175 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 181 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 196 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 196 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 202 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 202 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 202 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 208 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 208 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 208 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 208 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 214 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 214 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 220 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 227 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 235 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 241 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 241 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 241 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 241 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 247 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 247 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 247 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 247 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 253 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 253 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 259 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 266 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 266 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  { "title": "$Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 273 } },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 274 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "bargauge",
   "description": "Max 500 jobs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 274 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{pod_name=\"\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 280 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 280 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "% Idle"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 280 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 280 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 286 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 286 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 286 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 286 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 292 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 292 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 298 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_info) by (pod_name))",
     "legendFormat": "Current number of Pods"
    },
    {
     "expr": "max(sum(kube_node_status_capacity_pods) by (node))",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 305 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 305 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}