{
 "title": "Elasticearch JSON Parsing",
 "description": "Elasticsearch JSON Parsing Errors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customerName",
    "label": "Customer Name",
    "query": "aaa, aeads, air, analytair, atlas, audiencemodeling, audienceplatform, audiencetooling, audplat, ax,axidc, baratheon, campaigndev, campaignhub, contextdevelopers, contextsystem, cookiedough, csg,dataavailability, dataeng, dataengresponsys, dataingest, datalicense, datamatch, datanado, dataproducts,datausage, dbaidc, dirt, dmp, dmwf, dsdatafirst, dsi, eupanalytics, extplatformidc, finapps,fintech, greyjoy, hygiene, hyperloop, identity, idmds, imdata, infracore, infraplat, matchextract, measplat,measurement360, metadatavault, moatnginx, moatoutcomesadsdev, moatoutcomesia, moatoutcomesmethodology,moatoutcomesui, mpe, odccontextcog, odcqa, onramp,planner, platform, pmobi, pmotooling, pub,rtap, saasactivation, saascore, security, skywalker, stark, starkcog, techfeature, tyrell, xas,xrefproducer, yoda"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 }, "options": { "content": "# AWS PROD LOGGING\n" } },
  {
   "title": "EKS PROD: Parse Success vs Parse Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Parse Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\" AND message: \"namespace: {$customerName}\")",
     "timeField": "@timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "alias": "Parse Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_: \"json\" AND odc_customer: \"${customerName}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS PROD Publish Event Warnings",
   "type": "logs",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 2 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\" AND message: \"namespace: {$customerName}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS PROD Publish Event Warnings Total Count (All Teams)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 15 }, "options": { "content": "# AWS DEV LOGGING\n" } },
  {
   "title": "EKS DEV: Parse Success vs Parse Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Parse Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\" AND message: \"namespace: {$customerName}\")",
     "timeField": "@timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "alias": "Parse Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_: \"json\" AND odc_customer: \"${customerName}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS DEV Publish Event Warnings",
   "type": "logs",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 17 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\" AND message: \"namespace: {$customerName}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS DEV Publish Event Warnings Total Count (All Teams)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 30 }, "options": { "content": "# OCI US-PHX-C\n" } },
  {
   "title": "OCI US-PHX-C: Parse Success vs Parse Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Parse Failure",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\" AND message: \"namespace: {$customerName}\")",
     "timeField": "@timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "alias": "Parse Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "20m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_: \"json\" AND odc_customer: \"${customerName}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OCI US-PHX-C Publish Event Warnings",
   "type": "logs",
   "gridPos": { "h": 7, "w": 14, "x": 9, "y": 32 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND stream: \"stderr\" AND message: \"namespace: {$customerName}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OCI US-PHX-C Publish Event Warnings Total Count (All Teams)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "\"WARN\t[elasticsearch]\" AND \"Cannot index event publisher.Event\" AND NOT kubernetes.pod.name: cluster-filebeat-audit* AND NOT kubernetes.pod.name: filebeat-audit*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}