{
 "title": "ElasticSearch Prometheus Exporter",
 "tags": [
  "infra",
  "b2c",
  "elastic"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}*1) + scalar(elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}*2) + scalar(elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}*3)"
    }
   ]
  },
  {
   "title": "Read-Only Indices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_indices_settings_stats_read_only_indices{})"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})/count(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\",service!=\"es-exporter-elasticsearch-snapshot-exporter\"}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Disk Used",
   "type": "graph",
   "description": "Guage for disk space",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(((elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\"}) - (elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\"}))/ (elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\"})) * 100",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "graph",
   "description": "JVM Usage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(((elasticsearch_jvm_memory_used_bytes{cluster=~\"$cluster\"})/(elasticsearch_jvm_memory_max_bytes{cluster=~\"$cluster\"}))*100)",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "graph",
   "description": "Process CPU",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "elasticsearch_process_cpu_percent{cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Number of Snapshots",
   "type": "graph",
   "description": "Number of Snapshots",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "elasticsearch_snapshot_stats_number_of_snapshots",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Snapshot Seconds",
   "type": "graph",
   "description": "Snapshot Seconds",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "elasticsearch_snapshot_stats_snapshot_end_time_timestamp{repository=\"primary\",state=\"SUCCESS\"}-elasticsearch_snapshot_stats_snapshot_start_time_timestamp{repository=\"primary\",state=\"SUCCESS\"}",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Last Snapshot Failures",
   "type": "stat",
   "description": "Last Snapshot Failures",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "elasticsearch_snapshot_stats_snapshot_number_of_failures{repository=\"primary\",state=\"SUCCESS\"}",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Last Snapshot Indices",
   "type": "stat",
   "description": "Indices in Last Snapshot",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "elasticsearch_snapshot_stats_snapshot_number_of_indices{repository=\"primary\",state=\"SUCCESS\"}",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Last Snapshot Shards",
   "type": "stat",
   "description": "Last Snapshot Shards",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "elasticsearch_snapshot_stats_snapshot_total_shards{repository=\"primary\",state=\"SUCCESS\"}",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Oldest Snapshot Days",
   "type": "stat",
   "description": "Oldest Snapshot Days",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "ceil((time() - elasticsearch_snapshot_stats_oldest_snapshot_timestamp{repository=\"primary\"})/86400)",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Last Snapshot Hours",
   "type": "stat",
   "description": "Last Snapshot Hours",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "((time() - elasticsearch_snapshot_stats_snapshot_end_time_timestamp{repository=\"primary\",state=\"SUCCESS\"})/3600)",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "PartnerSync Snapshot Mins",
   "type": "stat",
   "description": "Last Snapshot Hours",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "((time() - elasticsearch_snapshot_stats_snapshot_end_time_timestamp{repository=\"partner_sync\",state=\"SUCCESS\"})/60)",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "total documents index rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_docs{cluster=\"us-phx-c-odelastic-prod-compliance\"}[5m]))",
     "legendFormat": "Documents  rate"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Queris/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=~\"$cluster\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{type}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 62 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 62 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemFree{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 62 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_active_count{cluster=~\"$cluster\", type!=\"management\"}) by (type)",
     "legendFormat": "Type: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\", type!=\"management\"}[5m])",
     "legendFormat": "{{ name }} {{ type }}"
    }
   ]
  },
  {
   "title": "Avg. CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(irate(node_cpu{cluster=~\"$cluster\"}[10s])) by(mode) *100",
     "legendFormat": "{{ mode }}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "failure_tstamp"
    }
   ]
  },
  {
   "title": "Avg Heap in 15min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=~\"$cluster\"}[15m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "RX/TX Rate 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_transport_rx_packets_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(elasticsearch_transport_tx_packets_total{cluster=~\"$cluster\"}[5m])) * -1",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{ name }} {{ gc }}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short", "label": "GCs" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "OS CPU - Incorrect for containers?",
   "type": "graph",
   "description": "CPU",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(((elasticsearch_os_cpu_percent{cluster=~\"$cluster\"})))",
     "legendFormat": "{{ name }} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}