{
 "title": "Infrastructure Platform Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Heartbeat Status",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "fields.platform",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "fields.service",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "fields.k8s-cluster",
       "id": "8",
       "settings": {
        "min_doc_count": 1,
        "missing": "n/a",
        "order": "desc",
        "orderBy": "_term",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "url.full",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "http.response.status_code",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      },
      {
       "field": "summary.up",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Heartbeat Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.full",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.rtt.total.us",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Up/Down History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "url.full",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "summary.up",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Up/Down History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}