{
 "title": "OFIM  Metrics us-iad-a",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "finapps-test,finapps-prod,finapps-dev"
   },
   {
    "name": "deploy",
    "query": "saasfileingest-ui-test,saasfileingest-ui-prod-bk,saasfileingest-ui-dev"
   }
  ]
 },
 "panels": [
  {
   "title": "Category Export File Size (MB)  VS Time Taken (mins)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time taken (mins)" }
   ],
   "targets": [
    {
     "expr": "(categoryInventory_export_duration_m_sum{response_size=~\".*\",job=\"$ns/$deploy\"})",
     "legendFormat": "{{response_size}} MB"
    }
   ]
  },
  {
   "title": "Application status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (container_name) (up{job=\"$ns/$deploy\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Average response time  of fileIngest_agg based on API",
   "type": "singlestat",
   "description": "average fileIngest_agg_duration",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 8 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (container_name) ((OFIM_Request_Duration_sum{route=~\".*/dataservice/api/v2/vis/agg.*/filestatus\",job=\"$ns/$deploy\"}/OFIM_Request_Duration_count{route=~\".*/dataservice/api/v2/vis/agg.*/filestatus\",job=\"$ns/$deploy\"}))\n"
    }
   ]
  },
  {
   "title": "Avg response time dataSourceIngest_agg_duration based on API",
   "type": "singlestat",
   "description": "average dataSourceIngest_agg_duration",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 8 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (container_name) ((OFIM_Request_Duration_sum{route=~\".*/dataservice/api/v2/vis/agg.*/sitehit\",job=\"$ns/$deploy\"}/OFIM_Request_Duration_count{route=~\".*/dataservice/api/v2/vis/agg.*/sitehit\",job=\"$ns/$deploy\"}))\n",
     "legendFormat": "{{routes}}"
    }
   ]
  },
  {
   "title": "Avg response time categoryInventory_search",
   "type": "singlestat",
   "description": "average categoryInventory_search_duration",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 8 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (container_name) ((OFIM_Request_Duration_sum{route=~\".*/dataservice/api/v2/vis/search.*/categoryinventory\",job=\"$ns/$deploy\"}/OFIM_Request_Duration_count{route=~\".*/dataservice/api/v2/vis/search.*/categoryinventory\",job=\"$ns/$deploy\"}))\n",
     "legendFormat": "{{routes}}"
    }
   ]
  },
  {
   "title": "Avg  response time of categoryInventory_agg",
   "type": "singlestat",
   "description": "Total  response time of categoryInventory_agg",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 8 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (container_name) ((OFIM_Request_Duration_sum{route=~\".*/dataservice/api/v2/vis/agg.*/categoryinventory \",job=\"$ns/$deploy\"}/OFIM_Request_Duration_count{route=~\".*/dataservice/api/v2/vis/agg.*/categoryinventory \",job=\"$ns/$deploy\"}))\n",
     "legendFormat": "{{routes}}"
    }
   ]
  },
  {
   "title": "Number of 302,304 responses",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (container_name) (http_request_duration_milliseconds_count{job=\"$ns/$deploy\", status=~\"30.\"})",
     "legendFormat": "path={{path}}"
    }
   ]
  },
  {
   "title": "50X responses",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " (http_request_duration_milliseconds_count{job=\"$ns/$deploy\", status=~\"50.\"})",
     "legendFormat": "path={{path}}"
    }
   ]
  },
  {
   "title": "400,403,404 responses",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(container_name)(http_request_duration_milliseconds_count{job=\"$ns/$deploy\", status=~\"40.\"})"
    }
   ]
  },
  {
   "title": "Node server memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " (nodejs_heap_size_used_bytes{job=~\"$ns/$deploy\"})",
     "legendFormat": " pod= {{ pod_name }}"
    }
   ]
  },
  {
   "title": "POD Memory Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$ns\",container_name =~\"$deploy.*\",pod_name=~\"$deploy.*\"} / on(pod_name) label_join(kube_pod_container_resource_requests_memory_bytes{pod=~\"$deploy.*\"},\n    \"pod_name\", \"\", \"pod\")* 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "POD Max Memory Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"$ns\",container_name =~\"$deploy.*\",pod_name=~\"$deploy.*\"} / on(pod_name) label_join(kube_pod_container_resource_limits_memory_bytes{pod=~\"$deploy.*\"},\n    \"pod_name\", \"\", \"pod\")* 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}